wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1672329338.472615
    t:
      1:
      - 5
      - 8
      - 53
      - 55
      2:
      - 5
      - 8
      - 53
      - 55
      3:
      - 23
      4: 3.8.8
      5: 0.13.7
      8:
      - 3
      - 5
